# Generated by Django 4.2.7 on 2023-11-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ongoing_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=100)),
                ('bill', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('estimated_delivery_date', models.DateField()),
                ('first_payment', models.IntegerField(blank=True, null=True)),
                ('second_payment', models.IntegerField(blank=True, null=True)),
                ('third_payment', models.IntegerField(blank=True, null=True)),
                ('due_amount', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Freelance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('linkedin', models.URLField()),
                ('total_earned', models.IntegerField(default=0)),
                ('skill', models.CharField(max_length=300)),
                ('due_amount', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancers', to='core.ongoing_project')),
            ],
        ),
        migrations.CreateModel(
            name='Completed_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=100)),
                ('bill', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('delivery_date', models.DateField()),
                ('warranty', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client')),
            ],
        ),
    ]
