# Generated by Django 4.2.7 on 2023-11-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Freelance',
            new_name='Freelancer',
        ),
    ]
