# Generated by Django 4.2.7 on 2023-11-17 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_freelance_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freelancers', to='core.ongoing_project'),
        ),
    ]
