# Generated by Django 4.2.7 on 2023-11-17 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_freelancer_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed_project',
            name='freelancer_linkedIn',
            field=models.URLField(default='sifat'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancers', to='core.ongoing_project'),
        ),
    ]
