# Generated by Django 4.2.7 on 2023-11-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_completed_project_freelancer_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('invoice', models.CharField(max_length=100)),
                ('problem', models.TextField()),
                ('solved', models.BooleanField(default=False)),
            ],
        ),
    ]
