# Generated by Django 4.2.7 on 2023-11-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='completed_project',
            name='freelancer_linkedIn',
            field=models.URLField(default='sifat.com'),
        ),
    ]
