# Generated by Django 4.2.7 on 2023-11-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_completed_project_options_ongoing_project_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed_project',
            name='url',
            field=models.TextField(blank=True, default='null', null=True),
        ),
    ]
