# Generated by Django 4.2.7 on 2023-11-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_completed_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed_project',
            name='services',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='ongoing_project',
            name='services',
            field=models.TextField(default='null'),
        ),
    ]
